#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

register:
    path: /api/register
    controller: App\Controller\RegisterController::register
    methods: ['POST']

api_birds:
    path: /api/birds
    methods: [POST, GET]
    controller: App\Controller\ApiController::postBirds

app_post:
    path: /api/post
    methods: [POST, GET]
    controller: App\Controller\PostController::likeBird

app_allbird:
    path: /api/allbirds
    methods: [POST, GET]
    controller: App\Controller\PostController::AllBird